apiVersion: v1
kind: Service
metadata:
  name: api-mesflix-service
spec:
  selector:
    app: api-mesflix # Debe coincidir con las labels del Deployment
  ports:
    - protocol: TCP
      port: 80 # Puerto por el que el servicio es accesible DENTRO del cluster
      targetPort: 8080 # Puerto al que apunta en los Pods (el containerPort)
  type: ClusterIP # O ClusterIP si solo es acceso interno, o NodePort para desarrollo
                    # LoadBalancer suele usarse para exponer a internet en proveedores cloud